from typing import Callable, Dict, List
from BaseClasses import CollectionState
from .RuleLogic import state_has_at_least

rule_data_list: List[Callable[[CollectionState, int], bool]] = [
    lambda state, player:
    True,  # Rule 0
    lambda state, player:
    state.has("Tablet", player, 3),  # Rule 1
    lambda state, player:
    state.has("Tablet", player, 2),  # Rule 2
    lambda state, player:
    state.has("Arithmometer", player),  # Rule 3
    lambda state, player:
    state.has("Loupe", player),  # Rule 4
    lambda state, player:
    state.has("Monster Flesh", player),  # Rule 5
    lambda state, player:
    state.has("Tablet", player),  # Rule 6
    lambda state, player:
    (state.has("Tablet", player, 3) and
     state.has("Crux Base", player) and
     state.has("Crux Tip", player) and
     state.has("Crux Body", player)),  # Rule 7
    lambda state, player:
    state.has("Supply Sphere Password", player),  # Rule 8
    lambda state, player:
    (state.has("Thunderclap Cap", player) and
     state.has("Shaolong Gui Shell", player) and
     state.has("Mandragora Root", player)),  # Rule 9
    lambda state, player:
    (state.has("Green Carbuncle Doll", player) or
     state.has("Red Carbuncle Doll", player)),  # Rule 10
    lambda state, player:
    state.has("Spectral Elixir", player),  # Rule 11
    lambda state, player:
    state.has("Cursed Dragon Claw", player),  # Rule 12
    lambda state, player:
    state.has("Rubber Ball", player),  # Rule 13
    lambda state, player:
    state.has("Quill Pen", player),  # Rule 14
    lambda state, player:
    state.has("Phantom Rose", player),  # Rule 15
    lambda state, player:
    state.has("Gysahl Greens", player),  # Rule 16
    lambda state, player:
    (state.has("Gysahl Greens", player) and
     state.has("Data Recorder", player)),  # Rule 17
    lambda state, player:
    (state.has("Gysahl Greens", player) and
     state.has("Aryas Apple", player, 2)),  # Rule 18
    lambda state, player:
    (state.has("Gysahl Greens", player) and
     state.has("Fragment of Mischief", player) and
     state.has("Fragment of Radiance", player) and
     state.has("Fragment of Smiles", player) and
     state.has("Fragment of Courage", player) and
     state.has("Fragment of Kindness", player)),  # Rule 19
    lambda state, player:
    (state.has("Gysahl Greens", player) and
     state.has("Goddess Glyphs", player) and
     state.has("Chaos Glyphs", player) and
     state.has("Plate Metal Fragment", player) and
     state.has("Silvered Metal Fragment", player) and
     state.has("Golden Metal Fragment", player)),  # Rule 20
    lambda state, player:
    (state.has("Gysahl Greens", player) and
     state.has("Goddess Glyphs", player) and
     state.has("Chaos Glyphs", player)),  # Rule 21
    lambda state, player:
    (state.has("ID Card", player) and
     state.has("Sneaking-In Special Ticket", player)),  # Rule 22
    lambda state, player:
    (state.has("Sneaking-In Special Ticket", player) and
     state.has("ID Card", player) and
     state.has("Midnight Mauve", player) and
     state.has("Serah's Pendant", player)),  # Rule 23
    lambda state, player:
    state.has("Sneaking-In Special Ticket", player),  # Rule 24
    lambda state, player:
    state.has("Musical Treasure Sphere Key", player),  # Rule 25
    lambda state, player:
    (state.has("Sneaking-In Special Ticket", player) and
     state.has("ID Card", player)),  # Rule 26
    lambda state, player:
    (state.has("Sneaking-In Special Ticket", player) and
     state.has("ID Card", player) and
     state.has("Midnight Mauve", player)),  # Rule 27
    lambda state, player:
    state.has("Music Satchel", player),  # Rule 28
    lambda state, player:
    state.has("Father's Letter", player),  # Rule 29
    lambda state, player:
    (state.has("Civet Musk", player) and
     state.has("Gordon Gourmet's Recipe", player) and
     state.has("Steak a la Civet", player)),  # Rule 30
    lambda state, player:
    (state.has("Nostalgic Score: Chorus", player) and
     state.has("Nostalgic Score: Refrain", player) and
     state.has("Nostalgic Score: Coda", player)),  # Rule 31
    lambda state, player:
    state.has("Civet Musk", player),  # Rule 32
    lambda state, player:
    (state.has("Civet Musk", player) and
     state.has("Gordon Gourmet's Recipe", player)),  # Rule 33
    lambda state, player:
    state.has("Proof of Legendary Title", player),  # Rule 34
    lambda state, player:
    (state.has("Jade Hair Comb", player) and
     state.has("Bronze Pocket Watch", player)),  # Rule 35
    lambda state, player:
    (state.has("Chocobo Girl's Phone No.", player) and
     state.has("ID Card", player) and
     state.has("Sneaking-In Special Ticket", player)),  # Rule 36
    lambda state, player:
    (state.has("Beloved's Gift", player) and
     state.has("Gysahl Greens", player)),  # Rule 37
    lambda state, player:
    (state.has("Key to the Sand Gate", player) and
     state.has("Key to the Green Gate", player)),  # Rule 38
    lambda state, player:
    (state.has("Bandit's Bloodseal", player) and
     state.has("Oath of the Merchants Guild", player)),  # Rule 39
    lambda state, player:
    state.has("Proof of Courage", player),  # Rule 40
    lambda state, player:
    state.has("Violet Amulet", player),  # Rule 41
    lambda state, player:
    (state.has("Lapis Lazuli", player) and
     state.has("Sneaking-In Special Ticket", player) and
     state.has("ID Card", player) and
     state.has("Midnight Mauve", player) and
     state.has("Serah's Pendant", player)),  # Rule 42
    lambda state, player:
    (state.has("Power Booster", player) and
     state.has("Sneaking-In Special Ticket", player) and
     state.has("ID Card", player) and
     state.has("Midnight Mauve", player) and
     state.has("Serah's Pendant", player)),  # Rule 43
    lambda state, player:
    (state.has("Moogle Dust", player) and
     state.has("Gysahl Greens", player)),  # Rule 44
    lambda state, player:
    (state.has("Old-Fashioned Photo Frame", player) and
     state.has("Gysahl Greens", player)),  # Rule 45
    lambda state, player:
    (state.has("Etro's Forbidden Tome", player) and
     state.has("Gysahl Greens", player)),  # Rule 46
    lambda state, player:
    state.has("Broken Gyroscope", player),  # Rule 47
    lambda state, player:
    (state.has("Golden Scarab", player) and
     state.has("Tablet", player, 2)),  # Rule 48
    lambda state, player:
    state.has("Seedhunter Membership Card", player),  # Rule 49
    lambda state, player:
    (state.has("Seedhunter Membership Card", player) and
     state.has("Moogle Fragment", player)),  # Rule 50
    lambda state, player:
    (state.has("Moogle Fragment", player) and
     state.has("Gysahl Greens", player) and
     state.has("Seedhunter Membership Card", player)),  # Rule 51
]

rule_data_table: Dict[str, Callable[[CollectionState, int], bool]] = {
    "Golden Scarab Treasure (1)": rule_data_list[0],
    "Oasis Lighthouse Treasure (1)": rule_data_list[0],
    "Grave of the Colossi Shrine Treasure (1)": rule_data_list[0],
    "Giant's Sandbox Treasure (1)": rule_data_list[0],
    "Golden Chamber Lower Treasure (1)": rule_data_list[0],
    "Giant's Sandbox Treasure (2)": rule_data_list[0],
    "Giant's Sandbox Treasure (3)": rule_data_list[0],
    "Giant's Sandbox Treasure (4)": rule_data_list[0],
    "Ruffian Outdoor Treasure (1)": rule_data_list[0],
    "Dry Floodlands Treasure (1)": rule_data_list[0],
    "Oasis Lighthouse Treasure (2)": rule_data_list[0],
    "Oasis Lighthouse Treasure (3)": rule_data_list[0],
    "Atomos's Sand Treasure (1)": rule_data_list[0],
    "Grave of the Colossi Treasure (1)": rule_data_list[0],
    "Grave of the Colossi Treasure (2)": rule_data_list[0],
    "Grave of the Colossi Treasure (3)": rule_data_list[0],
    "Atomos's Sand Treasure (2)": rule_data_list[0],
    "Ruffian 2nd Floor Treasure (1)": rule_data_list[0],
    "Temple Ruins Chamber of Dusk (Upper) Treasure (1)": rule_data_list[0],
    "Temple Ruins Chamber of Plenilune (Upper) Treasure (1)": rule_data_list[0],
    "Temple Ruins Chamber of Plenilune (Upper) Treasure (2)": rule_data_list[0],
    "Temple Ruins Chamber of Plenilune (Upper) Treasure (3)": rule_data_list[0],
    "Temple Ruins Chamber of Plenilune (Lower) Treasure (1)": rule_data_list[0],
    "Temple Ruins Chamber of Plenilune (Lower) Treasure (2)": rule_data_list[0],
    "Temple Ruins Chamber of Plenilune (Lower) Treasure (3)": rule_data_list[0],
    "Temple Ruins Sacred Grove Treasure (1)": rule_data_list[0],
    "Temple Ruins Golden Chamber (Upper) Treasure (1)": rule_data_list[0],
    "Dry Floodlands Shrine Treasure (1)": rule_data_list[0],
    "Temple Ruins Golden Chamber (Lower) Treasure (1)": rule_data_list[0],
    "Temple Ruins Golden Chamber (Lower) Treasure (2)": rule_data_list[0],
    "Temple Ruins Golden Chamber (Lower) Treasure (3)": rule_data_list[0],
    "Temple Ruins Scorched Earth (Lower) Treasure (1)": rule_data_list[0],
    "Temple Ruins Scorched Earth (Upper) Treasure (1)": rule_data_list[0],
    "Temple Ruins Scorched Earth (Upper) Treasure (2)": rule_data_list[0],
    "Temple Ruins Golden Chamber (Upper) Treasure (2)": rule_data_list[0],
    "Atomos's Sands Shrine Treasure (1)": rule_data_list[0],
    "Giant's Sandbox Treasure (5)": rule_data_list[0],
    "Dry Floodlands Treasure (2)": rule_data_list[0],
    "Grave of the Colossi Shrine Tablet (1)": rule_data_list[0],
    "Dry Floodlands Shrine Tablet (1)": rule_data_list[0],
    "Atomos's Sands Shrine Tablet (1)": rule_data_list[0],
    "Temple Ruins Mural Crux Base (1)": rule_data_list[1],
    "Temple Ruins Mural Crux Body (1)": rule_data_list[2],
    "Temple Ruins Mural Crux Tip (1)": rule_data_list[2],
    "Temple Ruins Bhakti Reward (1)": rule_data_list[0],
    "Grave of the Colossi Pilgrim's Crux (1)": rule_data_list[0],
    "Temple Ruins Scorched Earth Pilgrim's Crux (1)": rule_data_list[0],
    "Temple Ruins Golden Chamber (Lower) Pilgrim's Crux (1)": rule_data_list[0],
    "Temple Ruins Scorched Earth Pilgrim's Crux (2)": rule_data_list[0],
    "Dry Floodlands Pilgrim's Crux (1)": rule_data_list[0],
    "Atomos's Sands Pilgrim's Crux (1)": rule_data_list[0],
    "Giant's Sandbox Pilgrim's Crux (1)": rule_data_list[0],
    "Temple Ruins Sacred Grove Pilgrim's Crux (1)": rule_data_list[0],
    "Temple Ruins Sacred Grove Pilgrim's Crux (2)": rule_data_list[0],
    "Temple Ruins Golden Chamber (Upper) Pilgrim's Crux (1)": rule_data_list[0],
    "Temple Ruins Sacred Grove Pilgrim's Crux (3)": rule_data_list[0],
    "Temple Ruins Golden Chamber (Upper) Pilgrim's Crux (2)": rule_data_list[0],
    "Temple Ruins Sacred Grove Pilgrim's Crux (4)": rule_data_list[0],
    "Temple Ruins Golden Chamber (Lower) Pilgrim's Crux (2)": rule_data_list[0],
    "Atomos's Sands Loupe (1)": rule_data_list[0],
    "The Life of a Machine Quest (1)": rule_data_list[0],
    "The Life of a Machine Quest (2)": rule_data_list[0],
    "Old Rivals Quest (1)": rule_data_list[3],
    "Old Rivals Quest (2)": rule_data_list[3],
    "His Wife's Dream Quest (1)": rule_data_list[3],
    "His Wife's Dream Quest (2)": rule_data_list[3],
    "Tool of the Trade Quest (1)": rule_data_list[4],
    "Tool of the Trade Quest (2)": rule_data_list[4],
    "Adonis's Audition Quest (1)": rule_data_list[0],
    "Adonis's Audition Quest (2)": rule_data_list[0],
    "What Rough Beast Slouches Quest (1)": rule_data_list[5],
    "What Rough Beast Slouches Quest (2)": rule_data_list[5],
    "Skeletons In The Closet Quest (1)": rule_data_list[6],
    "Skeletons In The Closet Quest (2)": rule_data_list[6],
    "Last One Standing Quest (1)": rule_data_list[0],
    "Last One Standing Quest (2)": rule_data_list[0],
    "Last One Standing Quest (3)": rule_data_list[0],
    "What Rough Beast Slouches Libra Notes (1)": rule_data_list[0],
    "Dead Dunes Boss Drop (1)": rule_data_list[7],
    "Aeronite Missable Drop (1)": rule_data_list[0],
    "Cathedral Proof Of Courage (1)": rule_data_list[0],
    "Pilgrim's Passage Violet Amulet Treasure (1)": rule_data_list[0],
    "North Station Plaza Treasure (1)": rule_data_list[0],
    "The Avenue Treasure (1)": rule_data_list[0],
    "Gallery Steps Treasure (1)": rule_data_list[0],
    "2nd Ave Treasure (1)": rule_data_list[0],
    "Pilgrim's Passage (Grassy) Treasure (1)": rule_data_list[0],
    "Old Theater Platform Treasure (1)": rule_data_list[0],
    "The Warren Mangled Hill Treasure (1)": rule_data_list[0],
    "South Station (Supply Sphere) Treasure (1)": rule_data_list[8],
    "Warehouse District (Supply Sphere) Treasure (1)": rule_data_list[8],
    "Residences (Supply Sphere) Treasure (1)": rule_data_list[8],
    "Forsaken Graveyard Treasure (1)": rule_data_list[0],
    "Den Of Shadows Treasure (1)": rule_data_list[0],
    "Luxerion After 1st Phone (1)": rule_data_list[0],
    "Den Of Shadows Treasure (2)": rule_data_list[0],
    "Luxerion After 1st Phone (2)": rule_data_list[0],
    "Luxerion After 1st Phone (3)": rule_data_list[0],
    "Luxerion Marketplace Treasure (1)": rule_data_list[0],
    "Forsaken Graveyard Treasure (2)": rule_data_list[0],
    "1st Ave Rubber Ball (1)": rule_data_list[0],
    "Marketplace Doll (1)": rule_data_list[0],
    "North Station Plaza Doll (1)": rule_data_list[0],
    "Warehouse District Thunderclap Cap (1)": rule_data_list[0],
    "Luxerion Proof of Legendary Title (1)": rule_data_list[0],
    "Luxerion Ghost Phantom Rose (1)": rule_data_list[0],
    "Luxerion Marketplace Pen (1)": rule_data_list[0],
    "Baird Seedhunter Membership Card (1)": rule_data_list[0],
    "Virgil Supply Sphere Password (1)": rule_data_list[0],
    "Buy Shaolong Gui Shell (1)": rule_data_list[0],
    "Buy Mandragora Root (1)": rule_data_list[0],
    "Chocobo Emporium Spectral Elixir (1)": rule_data_list[9],
    "The Things She Lost Quest (1)": rule_data_list[10],
    "The Things She Lost Quest (2)": rule_data_list[10],
    "Where Are You, Holmes? Quest (1)": rule_data_list[0],
    "Where Are You, Holmes? Quest (2)": rule_data_list[0],
    "Where Are You, Holmes? Quest (3)": rule_data_list[0],
    "Like Clockwork Quest (1)": rule_data_list[0],
    "Like Clockwork Quest (2)": rule_data_list[0],
    "Dying Wish Quest (1)": rule_data_list[11],
    "Dying Wish Quest (2)": rule_data_list[11],
    "Suspicious Spheres Quest (1)": rule_data_list[8],
    "Suspicious Spheres Quest (2)": rule_data_list[8],
    "Born From Chaos Quest (1)": rule_data_list[12],
    "Born From Chaos Quest (2)": rule_data_list[12],
    "Born From Chaos Quest (3)": rule_data_list[12],
    "Born From Chaos Quest (4)": rule_data_list[12],
    "Soul Seeds Quest (1)": rule_data_list[0],
    "Soul Seeds Quest (2)": rule_data_list[0],
    "Faster Than Lightning Quest (1)": rule_data_list[0],
    "Faster Than Lightning Quest (2)": rule_data_list[0],
    "Treasured Ball Quest (1)": rule_data_list[13],
    "Treasured Ball Quest (2)": rule_data_list[13],
    "Talbot's Gratitude (1)": rule_data_list[13],
    "The Angel's Tears Quest (1)": rule_data_list[0],
    "The Angel's Tears Quest (2)": rule_data_list[0],
    "The Saint's Stone Quest (1)": rule_data_list[0],
    "The Saint's Stone Quest (2)": rule_data_list[0],
    "The Saint's Stone Quest (3)": rule_data_list[0],
    "Aremiah Service Entrance Key (1)": rule_data_list[0],
    "Whither Faith Quest (1)": rule_data_list[0],
    "Whither Faith Quest (2)": rule_data_list[0],
    "The Avid Reader Quest (1)": rule_data_list[0],
    "The Avid Reader Quest (2)": rule_data_list[0],
    "Buried Passion Quest (1)": rule_data_list[14],
    "Buried Passion Quest (2)": rule_data_list[14],
    "The Girl Who Cried Wolf Quest (1)": rule_data_list[0],
    "The Girl Who Cried Wolf Quest (2)": rule_data_list[0],
    "Stuck in a Gem Quest (1)": rule_data_list[0],
    "Stuck in a Gem Quest (2)": rule_data_list[0],
    "Get the Girl Quest (1)": rule_data_list[0],
    "Get the Girl Quest (2)": rule_data_list[0],
    "A Rose By Any Other Name Quest (1)": rule_data_list[15],
    "A Rose By Any Other Name Quest (2)": rule_data_list[15],
    "A Rose By Any Other Name Quest (3)": rule_data_list[15],
    "A Rose By Any Other Name Quest (4)": rule_data_list[15],
    "Voices from the Grave Quest (1)": rule_data_list[0],
    "Voices from the Grave Quest (2)": rule_data_list[0],
    "To Save the Sinless Quest (1)": rule_data_list[0],
    "To Save the Sinless Quest (2)": rule_data_list[0],
    "Replace Chronostasis (1)": rule_data_list[0],
    "Luxerion Boss Drop (1)": rule_data_list[0],
    "Luxerion Boss+ Only Missable Drop (1)": rule_data_list[0],
    "Moogle Village Moogle Dust Treasure (1)": rule_data_list[0],
    "Research Camp Photo Frame Treasure (1)": rule_data_list[0],
    "Poltae Etro's Forbidden Tome (1)": rule_data_list[0],
    "Eremite Plains Broken Gyroscope Treasure (1)": rule_data_list[16],
    "Aryas Village Treasure (1)": rule_data_list[0],
    "Jagd Woods Treasure (1)": rule_data_list[16],
    "The Grasslands Treasure (1)": rule_data_list[16],
    "Poltae Treasure (1)": rule_data_list[16],
    "Canopus Farms Treasure (1)": rule_data_list[0],
    "Rocky Crag Treasure (1)": rule_data_list[16],
    "The Grasslands Treasure (2)": rule_data_list[16],
    "Aryas Village Treasure (2)": rule_data_list[0],
    "The Grasslands Treasure (3)": rule_data_list[16],
    "Eremite Plains Treasure (1)": rule_data_list[16],
    "Eremite Plains Treasure (2)": rule_data_list[16],
    "Moogle Village Treasure (1)": rule_data_list[16],
    "City of Ruins Treasure (1)": rule_data_list[16],
    "Rocky Crag Treasure (2)": rule_data_list[16],
    "Rocky Crag Treasure (3)": rule_data_list[16],
    "Aryas Village Treasure (3)": rule_data_list[16],
    "Poltae Treasure (2)": rule_data_list[0],
    "Eremite Plains Crash Site Fragment (1)": rule_data_list[16],
    "Goddess Temple Treasure (1)": rule_data_list[16],
    "Goddess Temple Treasure (2)": rule_data_list[16],
    "Goddess Temple Treasure (3)": rule_data_list[16],
    "Goddess Temple Treasure (4)": rule_data_list[16],
    "Goddess Temple Treasure (5)": rule_data_list[16],
    "Goddess Temple Treasure (6)": rule_data_list[16],
    "Goddess Temple Treasure (7)": rule_data_list[16],
    "Goddess Temple Treasure (8)": rule_data_list[16],
    "Goddess Temple Treasure (9)": rule_data_list[16],
    "Dr Gysahl's Gysahl Greens (1)": rule_data_list[0],
    "Aryas Village Beloved's Gift Treasure (1)": rule_data_list[0],
    "Sarala Vegatable Seeds (1)": rule_data_list[16],
    "A Father's Request Quest (1)": rule_data_list[16],
    "A Father's Request Quest (2)": rule_data_list[16],
    "The Hunter's Challenge Quest (1)": rule_data_list[16],
    "The Hunter's Challenge Quest (2)": rule_data_list[16],
    "The Hunter's Challenge Quest (3)": rule_data_list[16],
    "A Final Cure Quest (1)": rule_data_list[16],
    "A Final Cure Quest (2)": rule_data_list[16],
    "A Final Cure Quest (3)": rule_data_list[16],
    "Fuzzy Search Quest (1)": rule_data_list[0],
    "Fuzzy Search Quest (2)": rule_data_list[0],
    "Fuzzy Search Quest (3)": rule_data_list[0],
    "Round 'em Up Quest (1)": rule_data_list[16],
    "Round 'em Up Quest (2)": rule_data_list[16],
    "Chocobo Cheer Quest (1)": rule_data_list[16],
    "Chocobo Cheer Quest (2)": rule_data_list[16],
    "Chocobo Cheer Quest (3)": rule_data_list[16],
    "Peace and Quiet, Kupo Quest (1)": rule_data_list[0],
    "Peace and Quiet, Kupo Quest (2)": rule_data_list[0],
    "Peace and Quiet, Kupo Quest (3)": rule_data_list[0],
    "Saving an Angel Quest (1)": rule_data_list[16],
    "Saving an Angel Quest (2)": rule_data_list[16],
    "Omega Point Quest (1)": rule_data_list[17],
    "Omega Point Quest (2)": rule_data_list[17],
    "The Old Man and the Field Quest (1)": rule_data_list[16],
    "The Old Man and the Field Quest (2)": rule_data_list[16],
    "Land of our Forebears Quest (1)": rule_data_list[16],
    "Land of our Forebears Quest (2)": rule_data_list[16],
    "A Taste of the Past Quest (1)": rule_data_list[18],
    "A Taste of the Past Quest (2)": rule_data_list[18],
    "A Taste of the Past Quest (3)": rule_data_list[18],
    "Dog, Doctor and Assistant Quest (1)": rule_data_list[16],
    "Dog, Doctor and Assistant Quest (2)": rule_data_list[16],
    "Main Quest 5 (1)": rule_data_list[19],
    "Main Quest 5 (2)": rule_data_list[19],
    "Main Quest 5 (3)": rule_data_list[19],
    "The Right Stuff Quest (1)": rule_data_list[16],
    "The Right Stuff Quest (2)": rule_data_list[16],
    "The Secret Lives of Sheep Quest (1)": rule_data_list[16],
    "The Secret Lives of Sheep Quest (2)": rule_data_list[16],
    "Where Are You, Moogle? Quest (1)": rule_data_list[0],
    "Where Are You, Moogle? Quest (2)": rule_data_list[0],
    "Where Are You, Moogle? Quest (3)": rule_data_list[0],
    "Mercy of a Goddess Quest (1)": rule_data_list[16],
    "Mercy of a Goddess Quest (2)": rule_data_list[16],
    "The Grail of Valhalla Quest (1)": rule_data_list[20],
    "The Grail of Valhalla Quest (2)": rule_data_list[20],
    "The Grail of Valhalla Quest (3)": rule_data_list[20],
    "To Live in Chaos Quest (1)": rule_data_list[16],
    "To Live in Chaos Quest (2)": rule_data_list[16],
    "To Live in Chaos Quest (3)": rule_data_list[16],
    "Killing Time Quest (1)": rule_data_list[16],
    "Killing Time Quest (2)": rule_data_list[16],
    "Matchmaker Quest (1)": rule_data_list[16],
    "Matchmaker Quest (2)": rule_data_list[16],
    "Mother and Daughter Quest (1)": rule_data_list[16],
    "Mother and Daughter Quest (2)": rule_data_list[16],
    "The Secret Lives of Sheep Mystery Egg (1)": rule_data_list[16],
    "Goddess Temple Goddess Glyphs (1)": rule_data_list[16],
    "Goddess Temple Chaos Glyphs (1)": rule_data_list[16],
    "Poltae Plate Metal Fragment (1)": rule_data_list[21],
    "Poltae Silvered Metal Fragment (1)": rule_data_list[21],
    "Poltae Gold Metal Fragment (1)": rule_data_list[21],
    "Research Camp Data Recorder (1)": rule_data_list[16],
    "Aryas Village Apple (1)": rule_data_list[16],
    "Aryas Village Apple (2)": rule_data_list[16],
    "Aryas Village Apple (3)": rule_data_list[16],
    "Wildlands Boss Drop (1)": rule_data_list[16],
    "Reveler's Quarter Lapis Lazuli Treasure (1)": rule_data_list[0],
    "Industrial Area Power Booster (1)": rule_data_list[22],
    "Tunnel Oath of the Merchants Guild Treasure (1)": rule_data_list[0],
    "Industrial Area Jade Hair Comb (1)": rule_data_list[23],
    "Industrial Area Bronze Pocket Watch (1)": rule_data_list[24],
    "Chocobo Girl Poster (1)": rule_data_list[0],
    "Glutton's Quarter Treasure (1)": rule_data_list[0],
    "Aromatic Market Treasure (1)": rule_data_list[0],
    "Central Ave Treasure (1)": rule_data_list[0],
    "Coliseum Square Treasure (1)": rule_data_list[0],
    "Tour Guide Sneaking-In Special Ticket (1)": rule_data_list[0],
    "Warehouse District Id Card (1)": rule_data_list[24],
    "Coliseum Square (Musical) Treasure (1)": rule_data_list[25],
    "Cactuar Statue (Musical) Treasure (1)": rule_data_list[25],
    "Station (Musical) Treasure (1)": rule_data_list[25],
    "Cactuar Statue Treasure (1)": rule_data_list[0],
    "Reveler's Quarter Treasure (1)": rule_data_list[0],
    "Augur's Quarter Treasure (1)": rule_data_list[26],
    "Patron's Palace Treasure (1)": rule_data_list[27],
    "Hawker's Row Treasure (1)": rule_data_list[0],
    "Augur's Quarter Treasure (2)": rule_data_list[26],
    "Warehouse District Treasure (1)": rule_data_list[24],
    "Augur's Quarter Treasure (3)": rule_data_list[22],
    "Supply Line Treasure (1)": rule_data_list[24],
    "Industrial Area Treasure (1)": rule_data_list[24],
    "Lower City Treasure (1)": rule_data_list[0],
    "Glutton's Quarter Treasure (2)": rule_data_list[0],
    "Reveler's Quarter Treasure (2)": rule_data_list[0],
    "Patron's Palace Treasure (2)": rule_data_list[27],
    "Patron's Palace Treasure (3)": rule_data_list[27],
    "Patron's Palace Treasure (4)": rule_data_list[27],
    "Patron's Palace Treasure (5)": rule_data_list[27],
    "Slaughterhouse Special Fragment of Courage (1)": rule_data_list[16],
    "Slaughterhouse (1)": rule_data_list[0],
    "Slaughterhouse (2)": rule_data_list[0],
    "Slaughterhouse (3)": rule_data_list[0],
    "Slaughterhouse (4)": rule_data_list[0],
    "Slaughterhouse (5)": rule_data_list[0],
    "Slaughterhouse (6)": rule_data_list[0],
    "Slaughterhouse (7)": rule_data_list[0],
    "Slaughterhouse (8)": rule_data_list[0],
    "Slaughterhouse (9)": rule_data_list[0],
    "Slaughterhouse (10)": rule_data_list[0],
    "The Fighting Actress Slaughterhouse (1)": rule_data_list[26],
    "The Fighting Actress Slaughterhouse (2)": rule_data_list[26],
    "The Fighting Actress Slaughterhouse (3)": rule_data_list[26],
    "The Fighting Actress Slaughterhouse (4)": rule_data_list[26],
    "Tanbam's Taboo Slaughterhouse (1)": rule_data_list[23],
    "Chocobo Girl Miqo'te Dress (1)": rule_data_list[0],
    "Director Femme Fetale (1)": rule_data_list[27],
    "Fireworks in a Bottle Quest (1)": rule_data_list[26],
    "Fireworks in a Bottle Quest (2)": rule_data_list[26],
    "The Fighting Actress Quest (1)": rule_data_list[26],
    "The Fighting Actress Quest (2)": rule_data_list[26],
    "Songless Diva Quest (1)": rule_data_list[28],
    "Songless Diva Quest (2)": rule_data_list[28],
    "Stolen Things Quest (1)": rule_data_list[29],
    "Stolen Things Quest (2)": rule_data_list[29],
    "Fireworks for a Steal Quest (1)": rule_data_list[26],
    "Fireworks for a Steal Quest (2)": rule_data_list[26],
    "A Testing Proposition Quest (1)": rule_data_list[0],
    "A Testing Proposition Quest (2)": rule_data_list[0],
    "Last Date Quest (1)": rule_data_list[23],
    "Last Date Quest (2)": rule_data_list[23],
    "Free Will Quest (1)": rule_data_list[0],
    "Free Will Quest (2)": rule_data_list[0],
    "Free Will Quest (3)": rule_data_list[0],
    "Friends Forever Quest (1)": rule_data_list[23],
    "Friends Forever Quest (2)": rule_data_list[23],
    "Friends Forever Quest (3)": rule_data_list[23],
    "Family Food Quest (1)": rule_data_list[30],
    "Family Food Quest (2)": rule_data_list[30],
    "Tanbam's Taboo Quest (1)": rule_data_list[23],
    "Tanbam's Taboo Quest (2)": rule_data_list[23],
    "Play It for Me Quest (1)": rule_data_list[31],
    "Play It for Me Quest (2)": rule_data_list[31],
    "Adoring Adornments Quest (1)": rule_data_list[26],
    "Adoring Adornments Quest (2)": rule_data_list[26],
    "Adoring Candice Quest (1)": rule_data_list[23],
    "Adoring Candice Quest (2)": rule_data_list[23],
    "Adoring Candice Quest (3)": rule_data_list[23],
    "Death Safari Quest (1)": rule_data_list[26],
    "Death Safari Quest (2)": rule_data_list[26],
    "Death Safari Quest (3)": rule_data_list[26],
    "Death Safari Quest (4)": rule_data_list[26],
    "Death Safari Quest (5)": rule_data_list[26],
    "Death Game Quest (1)": rule_data_list[26],
    "Death Game Quest (2)": rule_data_list[26],
    "Death Game Quest (3)": rule_data_list[26],
    "Morris Musical Treasure Sphere Key (1)": rule_data_list[0],
    "Patron's Palace Serah's Pendant (1)": rule_data_list[27],
    "Gordon Gourmet's Recipe (1)": rule_data_list[32],
    "Seedy Steak a la Civet (1)": rule_data_list[33],
    "Gregory Father's Letter (1)": rule_data_list[0],
    "Tanbam's Taboo Libra Notes (1)": rule_data_list[23],
    "Yusnaan Boss Drop (1)": rule_data_list[23],
    "Initial 3rd Garb (1)": rule_data_list[0],
    "Initial 3rd Garb (2)": rule_data_list[0],
    "Initial 3rd Garb (3)": rule_data_list[0],
    "Ark Day 1 (1)": rule_data_list[0],
    "Ark Day 1 (2)": rule_data_list[0],
    "Ark Day 1 (3)": rule_data_list[0],
    "Ark Day 1 (4)": rule_data_list[0],
    "Ark Day 1 (5)": rule_data_list[0],
    "Ark Day 2 (1)": rule_data_list[0],
    "Ark Day 2 (2)": rule_data_list[0],
    "Ark Day 2 (3)": rule_data_list[0],
    "Ark Day 3 (1)": rule_data_list[0],
    "Ark Day 4 (1)": rule_data_list[0],
    "Ark Day 4 (2)": rule_data_list[0],
    "Ark Day 5 (1)": rule_data_list[0],
    "Ark Day 6 (1)": rule_data_list[0],
    "Ark Day 7 (1)": rule_data_list[0],
    "Ark Day 8 (1)": rule_data_list[0],
    "Ark Day 9 (1)": rule_data_list[0],
    "Ark Day 10 (1)": rule_data_list[0],
    "Ark Day 11 (1)": rule_data_list[0],
    "Ark Day 12 (1)": rule_data_list[0],
    "Ark Final Day (1)": rule_data_list[0],
    "Ark Final Day (2)": rule_data_list[0],
    "Ark Final Day (3)": rule_data_list[0],
    "Ark Extra Day (1)": rule_data_list[0],
    "Replace Curaga (1)": rule_data_list[0],
    "Replace Teleport (1)": rule_data_list[0],
    "Replace Escape (1)": rule_data_list[0],
    "Flower in the Sands CoP Quest (1)": rule_data_list[0],
    "Flower in the Sands CoP Quest (2)": rule_data_list[0],
    "Biologically Speaking CoP Quest (1)": rule_data_list[0],
    "Biologically Speaking CoP Quest (2)": rule_data_list[0],
    "The Real Client CoP Quest (1)": rule_data_list[0],
    "The Real Client CoP Quest (2)": rule_data_list[0],
    "The Real Client CoP Quest (3)": rule_data_list[0],
    "For My Child CoP Quest (1)": rule_data_list[0],
    "For My Child CoP Quest (2)": rule_data_list[0],
    "For My Child CoP Quest (3)": rule_data_list[0],
    "Bandits' New Weapon CoP Quest (1)": rule_data_list[0],
    "Bandits' New Weapon CoP Quest (2)": rule_data_list[0],
    "Bandits' New Weapon CoP Quest (3)": rule_data_list[0],
    "Banned Goods CoP Quest (1)": rule_data_list[0],
    "Banned Goods CoP Quest (2)": rule_data_list[0],
    "Banned Goods CoP Quest (3)": rule_data_list[0],
    "Climbing The Ranks I CoP Quest (1)": rule_data_list[0],
    "Climbing The Ranks I CoP Quest (2)": rule_data_list[0],
    "Miracle Vintage CoP Quest (1)": rule_data_list[0],
    "Miracle Vintage CoP Quest (2)": rule_data_list[0],
    "Miracle Vintage CoP Quest (3)": rule_data_list[0],
    "Climbing The Ranks II CoP Quest (1)": rule_data_list[0],
    "Climbing The Ranks II CoP Quest (2)": rule_data_list[0],
    "Heightened Security CoP Quest (1)": rule_data_list[0],
    "Heightened Security CoP Quest (2)": rule_data_list[0],
    "Heightened Security CoP Quest (3)": rule_data_list[0],
    "Desert Cleanup CoP Quest (1)": rule_data_list[0],
    "Desert Cleanup CoP Quest (2)": rule_data_list[0],
    "Desert Cleanup CoP Quest (3)": rule_data_list[0],
    "A Treasure for a God CoP Quest (1)": rule_data_list[7],
    "A Treasure for a God CoP Quest (2)": rule_data_list[7],
    "Lucky Charm CoP Quest (1)": rule_data_list[0],
    "Lucky Charm CoP Quest (2)": rule_data_list[0],
    "Supply and Demand CoP Quest (1)": rule_data_list[0],
    "Supply and Demand CoP Quest (2)": rule_data_list[0],
    "Supply and Demand CoP Quest (3)": rule_data_list[0],
    "A New Application CoP Quest (1)": rule_data_list[30],
    "A New Application CoP Quest (2)": rule_data_list[30],
    "A New Application CoP Quest (3)": rule_data_list[30],
    "Pride And Greed I CoP Quest (1)": rule_data_list[0],
    "Pride And Greed I CoP Quest (2)": rule_data_list[0],
    "Pride And Greed I CoP Quest (3)": rule_data_list[0],
    "Pride And Greed II CoP Quest (1)": rule_data_list[0],
    "Pride And Greed II CoP Quest (2)": rule_data_list[0],
    "Pride And Greed II CoP Quest (3)": rule_data_list[0],
    "Pride And Greed III CoP Quest (1)": rule_data_list[0],
    "Pride And Greed III CoP Quest (2)": rule_data_list[0],
    "Pride And Greed III CoP Quest (3)": rule_data_list[0],
    "Revenge Is Sweet CoP Quest (1)": rule_data_list[0],
    "Revenge Is Sweet CoP Quest (2)": rule_data_list[0],
    "Gift of Gratitude CoP Quest (1)": rule_data_list[0],
    "Gift of Gratitude CoP Quest (2)": rule_data_list[0],
    "Gift of Gratitude CoP Quest (3)": rule_data_list[0],
    "A Song for God CoP Quest (1)": rule_data_list[0],
    "A Song for God CoP Quest (2)": rule_data_list[0],
    "A Song for God CoP Quest (3)": rule_data_list[0],
    "Slay the Machine CoP Quest (1)": rule_data_list[0],
    "Slay the Machine CoP Quest (2)": rule_data_list[0],
    "Enchanted Brush CoP Quest (1)": rule_data_list[0],
    "Enchanted Brush CoP Quest (2)": rule_data_list[0],
    "Enchanted Brush CoP Quest (3)": rule_data_list[0],
    "Heretics' Beasts CoP Quest (1)": rule_data_list[0],
    "Heretics' Beasts CoP Quest (2)": rule_data_list[0],
    "Heretics' Beasts CoP Quest (3)": rule_data_list[0],
    "Grave of a Bounty Hunter CoP Quest (1)": rule_data_list[0],
    "Grave of a Bounty Hunter CoP Quest (2)": rule_data_list[0],
    "Grave of a Bounty Hunter CoP Quest (3)": rule_data_list[0],
    "Inventive Seamstress CoP Quest (1)": rule_data_list[0],
    "Inventive Seamstress CoP Quest (2)": rule_data_list[0],
    "Puppeteer's Lament CoP Quest (1)": rule_data_list[0],
    "Puppeteer's Lament CoP Quest (2)": rule_data_list[0],
    "Puppeteer's Lament CoP Quest (3)": rule_data_list[0],
    "Revenge has Teeth CoP Quest (1)": rule_data_list[0],
    "Revenge has Teeth CoP Quest (2)": rule_data_list[0],
    "Night Patrol CoP Quest (1)": rule_data_list[0],
    "Night Patrol CoP Quest (2)": rule_data_list[0],
    "Night Patrol CoP Quest (3)": rule_data_list[0],
    "Trapped CoP Quest (1)": rule_data_list[0],
    "Trapped CoP Quest (2)": rule_data_list[0],
    "Trapped CoP Quest (3)": rule_data_list[0],
    "Trapped CoP Quest (4)": rule_data_list[0],
    "Mythical Badge CoP Quest (1)": rule_data_list[34],
    "Mythical Badge CoP Quest (2)": rule_data_list[34],
    "Mythical Badge CoP Quest (3)": rule_data_list[34],
    "Sun Flower CoP Quest (1)": rule_data_list[0],
    "Sun Flower CoP Quest (2)": rule_data_list[0],
    "Moon Flower CoP Quest (1)": rule_data_list[0],
    "Moon Flower CoP Quest (2)": rule_data_list[0],
    "Moon Flower CoP Quest (3)": rule_data_list[0],
    "Secret of the Chocoborel CoP Quest (1)": rule_data_list[0],
    "Secret of the Chocoborel CoP Quest (2)": rule_data_list[0],
    "Secret of the Chocoborel CoP Quest (3)": rule_data_list[0],
    "Wildlands In Danger! CoP Quest (1)": rule_data_list[16],
    "Wildlands In Danger! CoP Quest (2)": rule_data_list[16],
    "Wildlands In Danger! CoP Quest (3)": rule_data_list[16],
    "Hunting the Hunter CoP Quest (1)": rule_data_list[0],
    "Hunting the Hunter CoP Quest (2)": rule_data_list[0],
    "Hunting the Hunter CoP Quest (3)": rule_data_list[0],
    "Forget Me Not CoP Quest (1)": rule_data_list[0],
    "Forget Me Not CoP Quest (2)": rule_data_list[0],
    "Forget Me Not CoP Quest (3)": rule_data_list[0],
    "A Word of Thanks CoP Quest (1)": rule_data_list[0],
    "A Word of Thanks CoP Quest (2)": rule_data_list[0],
    "A Word of Thanks CoP Quest (3)": rule_data_list[0],
    "Fresh Fertilizer CoP Quest (1)": rule_data_list[16],
    "Fresh Fertilizer CoP Quest (2)": rule_data_list[16],
    "Fresh Fertilizer CoP Quest (3)": rule_data_list[16],
    "For the Future CoP Quest (1)": rule_data_list[0],
    "For the Future CoP Quest (2)": rule_data_list[0],
    "For the Future CoP Quest (3)": rule_data_list[0],
    "Dumpling Cook-Off CoP Quest (1)": rule_data_list[0],
    "Dumpling Cook-Off CoP Quest (2)": rule_data_list[0],
    "Dumpling Cook-Off CoP Quest (3)": rule_data_list[0],
    "Brain Over Brawn CoP Quest (1)": rule_data_list[0],
    "Brain Over Brawn CoP Quest (2)": rule_data_list[0],
    "Brain Over Brawn CoP Quest (3)": rule_data_list[0],
    "Hunter's Challenge CoP Quest (1)": rule_data_list[0],
    "Hunter's Challenge CoP Quest (2)": rule_data_list[0],
    "Hunter's Challenge CoP Quest (3)": rule_data_list[0],
    "A Secret Wish CoP Quest (1)": rule_data_list[0],
    "A Secret Wish CoP Quest (2)": rule_data_list[0],
    "A Secret Wish CoP Quest (3)": rule_data_list[0],
    "Moghan's Plea CoP Quest (1)": rule_data_list[0],
    "Moghan's Plea CoP Quest (2)": rule_data_list[0],
    "Moghan's Plea CoP Quest (3)": rule_data_list[0],
    "What's in a Brew? CoP Quest (1)": rule_data_list[16],
    "What's in a Brew? CoP Quest (2)": rule_data_list[16],
    "What's in a Brew? CoP Quest (3)": rule_data_list[16],
    "What's in a Brew? CoP Quest (4)": rule_data_list[16],
    "A Prayer to a Goddess CoP Quest (1)": rule_data_list[0],
    "A Prayer to a Goddess CoP Quest (2)": rule_data_list[0],
    "A Prayer to a Goddess CoP Quest (3)": rule_data_list[0],
    "Gatekeeper's Curiosity CoP Quest (1)": rule_data_list[0],
    "Gatekeeper's Curiosity CoP Quest (2)": rule_data_list[0],
    "Echoes of a Drum CoP Quest (1)": rule_data_list[0],
    "Echoes of a Drum CoP Quest (2)": rule_data_list[0],
    "Echoes of a Drum CoP Quest (3)": rule_data_list[0],
    "A Voice From Below CoP Quest (1)": rule_data_list[0],
    "A Voice From Below CoP Quest (2)": rule_data_list[0],
    "A Voice From Below CoP Quest (3)": rule_data_list[0],
    "Chocobo Chow CoP Quest (1)": rule_data_list[16],
    "Chocobo Chow CoP Quest (2)": rule_data_list[16],
    "Chocobo Chow CoP Quest (3)": rule_data_list[16],
    "Sylkis Secrets CoP Quest (1)": rule_data_list[16],
    "Sylkis Secrets CoP Quest (2)": rule_data_list[16],
    "Sylkis Secrets CoP Quest (3)": rule_data_list[16],
    "Digging Mole CoP Quest (1)": rule_data_list[16],
    "Digging Mole CoP Quest (2)": rule_data_list[16],
    "Digging Mole CoP Quest (3)": rule_data_list[16],
    "Two Together CoP Quest (1)": rule_data_list[0],
    "Two Together CoP Quest (2)": rule_data_list[0],
    "Two Together CoP Quest (3)": rule_data_list[0],
    "Emergency Treatment CoP Quest (1)": rule_data_list[16],
    "Emergency Treatment CoP Quest (2)": rule_data_list[16],
    "Emergency Treatment CoP Quest (3)": rule_data_list[16],
    "Moogle Gourmand CoP Quest (1)": rule_data_list[16],
    "Moogle Gourmand CoP Quest (2)": rule_data_list[16],
    "Moogle Gourmand CoP Quest (3)": rule_data_list[16],
    "Secret Machine CoP Quest (1)": rule_data_list[0],
    "Secret Machine CoP Quest (2)": rule_data_list[0],
    "Soulful Horn CoP Quest (1)": rule_data_list[0],
    "Soulful Horn CoP Quest (2)": rule_data_list[0],
    "Soulful Horn CoP Quest (3)": rule_data_list[0],
    "A Dangerous Cocktail CoP Quest (1)": rule_data_list[0],
    "A Dangerous Cocktail CoP Quest (2)": rule_data_list[0],
    "Source of Inspiration CoP Quest (1)": rule_data_list[0],
    "Source of Inspiration CoP Quest (2)": rule_data_list[0],
    "Youth Potion CoP Quest (1)": rule_data_list[0],
    "Youth Potion CoP Quest (2)": rule_data_list[0],
    "Youth Potion CoP Quest (3)": rule_data_list[0],
    "Beast Summoner CoP Quest (1)": rule_data_list[0],
    "Beast Summoner CoP Quest (2)": rule_data_list[0],
    "Beast Summoner CoP Quest (3)": rule_data_list[0],
    "What Seekers Seek CoP Quest (1)": rule_data_list[0],
    "What Seekers Seek CoP Quest (2)": rule_data_list[0],
    "What Seekers Seek CoP Quest (3)": rule_data_list[0],
    "True Colors CoP Quest (1)": rule_data_list[0],
    "True Colors CoP Quest (2)": rule_data_list[0],
    "True Colors CoP Quest (3)": rule_data_list[0],
    "Ultimate Craving CoP Quest (1)": rule_data_list[0],
    "Ultimate Craving CoP Quest (2)": rule_data_list[0],
    "Ultimate Craving CoP Quest (3)": rule_data_list[0],
    "Ultimate Craving CoP Quest (4)": rule_data_list[0],
    "Spell for Spell CoP Quest (1)": rule_data_list[0],
    "Spell for Spell CoP Quest (2)": rule_data_list[0],
    "Spell for Spell CoP Quest (3)": rule_data_list[0],
    "Unfired Firework CoP Quest (1)": rule_data_list[23],
    "Unfired Firework CoP Quest (2)": rule_data_list[23],
    "Unfired Firework CoP Quest (3)": rule_data_list[23],
    "Time Doesn't Heal CoP Quest (1)": rule_data_list[35],
    "Time Doesn't Heal CoP Quest (2)": rule_data_list[35],
    "Time Doesn't Heal CoP Quest (3)": rule_data_list[35],
    "A Man for a Chocobo Girl CoP Quest (1)": rule_data_list[36],
    "A Man for a Chocobo Girl CoP Quest (2)": rule_data_list[36],
    "A Man for a Chocobo Girl CoP Quest (3)": rule_data_list[36],
    "Rebuilding CoP Quest (1)": rule_data_list[23],
    "Rebuilding CoP Quest (2)": rule_data_list[23],
    "Global: Key To Her Heart CoP Quest (1)": rule_data_list[37],
    "Global: Key To Her Heart CoP Quest (2)": rule_data_list[37],
    "Global: Key To Her Heart CoP Quest (3)": rule_data_list[37],
    "Global: Roadworks I CoP Quest (1)": rule_data_list[0],
    "Global: Roadworks I CoP Quest (2)": rule_data_list[0],
    "Global: Roadworks I CoP Quest (3)": rule_data_list[0],
    "Global: Roadworks II CoP Quest (1)": rule_data_list[38],
    "Global: Roadworks II CoP Quest (2)": rule_data_list[38],
    "Global: Roadworks II CoP Quest (3)": rule_data_list[38],
    "Global: Roadworks III CoP Quest (1)": rule_data_list[39],
    "Global: Roadworks III CoP Quest (2)": rule_data_list[39],
    "Global: Roadworks III CoP Quest (3)": rule_data_list[39],
    "Global: A Girl's Challenge CoP Quest (1)": rule_data_list[40],
    "Global: A Girl's Challenge CoP Quest (2)": rule_data_list[40],
    "Global: What's Left Behind CoP Quest (1)": rule_data_list[41],
    "Global: What's Left Behind CoP Quest (2)": rule_data_list[41],
    "Global: Seeing The Dawn CoP Quest (1)": rule_data_list[42],
    "Global: Seeing The Dawn CoP Quest (2)": rule_data_list[42],
    "Global: Staying Sharp CoP Quest (1)": rule_data_list[43],
    "Global: Staying Sharp CoP Quest (2)": rule_data_list[43],
    "Global: Where Moogles Be CoP Quest (1)": rule_data_list[44],
    "Global: Where Moogles Be CoP Quest (2)": rule_data_list[44],
    "Global: Fading Prayer CoP Quest (1)": rule_data_list[45],
    "Global: Fading Prayer CoP Quest (2)": rule_data_list[45],
    "Global: Forbidden Tome CoP Quest (1)": rule_data_list[46],
    "Global: Forbidden Tome CoP Quest (2)": rule_data_list[46],
    "Global: Shoot For The Sky CoP Quest (1)": rule_data_list[47],
    "Global: Shoot For The Sky CoP Quest (2)": rule_data_list[47],
    "Global: Shoot For The Sky CoP Quest (3)": rule_data_list[47],
    "Global: Digging Mysteries CoP Quest (1)": rule_data_list[48],
    "Global: Digging Mysteries CoP Quest (2)": rule_data_list[48],
    "Global: Digging Mysteries CoP Quest (3)": rule_data_list[48],
    "10 Soul Seeds (1)": rule_data_list[49],
    "20 Soul Seeds (1)": rule_data_list[49],
    "30 Soul Seeds (1)": rule_data_list[49],
    "40 Soul Seeds (1)": rule_data_list[49],
    "50 Soul Seeds (1)": rule_data_list[49],
    "Soul Seeds Fragment of Radiance (1)": rule_data_list[50],
    "1 Unappraised (1)": rule_data_list[4],
    "5 Unappraised (1)": rule_data_list[4],
    "10 Unappraised (1)": rule_data_list[4],
    "20 Unappraised (1)": rule_data_list[4],
    "50 Unappraised (1)": rule_data_list[4],
    "Ultimate Lair Boss Drop (1)": rule_data_list[0],
    "Gorgonopsid Omega Drop (1)": rule_data_list[0],
    "Zaltys Omega Drop (1)": rule_data_list[0],
    "Miniflan Omega Drop (1)": rule_data_list[0],
    "Hanuman Omega Drop (1)": rule_data_list[0],
    "Zomok Omega Drop (1)": rule_data_list[0],
    "Goblin Omega Drop (1)": rule_data_list[0],
    "Gremlin Omega Drop (1)": rule_data_list[0],
    "Niblet Omega Drop (1)": rule_data_list[0],
    "Goblot Omega Drop (1)": rule_data_list[0],
    "Triffid Omega Drop (1)": rule_data_list[0],
    "Schrodinger Omega Drop (1)": rule_data_list[0],
    "Earth Eater Omega Drop (1)": rule_data_list[0],
    "Chocobo Eater Omega Drop (1)": rule_data_list[0],
    "Desert Sahagin Omega Drop (1)": rule_data_list[0],
    "Rafflesia Omega Drop (1)": rule_data_list[0],
    "Cactuar Omega Drop (1)": rule_data_list[0],
    "Gurangatch Omega Drop (1)": rule_data_list[0],
    "Skata'ne Omega Drop (1)": rule_data_list[0],
    "Dryad Omega Drop (1)": rule_data_list[0],
    "Dreadnought Omega Drop (1)": rule_data_list[0],
    "Hoplite Omega Drop (1)": rule_data_list[0],
    "Aster Protoflorian Omega Drop (1)": rule_data_list[0],
    "Gaunt Omega Drop (1)": rule_data_list[0],
    "Ectopudding Omega Drop (1)": rule_data_list[0],
    "Meonekton Omega Drop (1)": rule_data_list[0],
    "Cyclops Omega Drop (1)": rule_data_list[0],
    "Reaver Omega Drop (1)": rule_data_list[0],
    "Skeleton Omega Drop (1)": rule_data_list[0],
    "Ultimate Lair Floor 29 (1)": rule_data_list[0],
    "Ultimate Lair Floor 30 (1)": rule_data_list[0],
    "Ultimate Lair Floor 31 (1)": rule_data_list[0],
    "Ultimate Lair Floor 32 (1)": rule_data_list[0],
    "Ultimate Lair Boss Reward (1)": rule_data_list[0],
    "Arcangeli Omega Drop (1)": rule_data_list[0],
    "Sugriva Omega Drop (1)": rule_data_list[0],
    "Chimera Omega Drop (1)": rule_data_list[0],
    "Final Day Altar Of Salvation (1)": rule_data_list[0],
    "Final Day Altar Of Judgment (1)": rule_data_list[0],
    "Final Day Altar Of Atonement (1)": rule_data_list[0],
    "Final Day Altar Of Birth (1)": rule_data_list[0],
    "Final Day Temple Of Light (1)": rule_data_list[0],
    "Final Day Temple Of Light (2)": rule_data_list[0],
    "Final Day Temple Of Light (3)": rule_data_list[0],
    "Final Day Ultima Weapon (1)": rule_data_list[0],
    "Final Day Ultima Shield (1)": rule_data_list[0],
    "Cactair Fragment of Kindness (1)": rule_data_list[0],
    "Goblots Arithmometer (1)": rule_data_list[0],
    "Aeronite Monster Flesh (1)": rule_data_list[0],
    "Zomok Cursed Dragon Claw (1)": rule_data_list[0],
    "Gremlins Music Satchel (1)": rule_data_list[0],
    "Schrodinger Civet Musk (1)": rule_data_list[0],
    "Hint 1-1 Hint Event (1)": rule_data_list[0],
    "Hint 1-2 Hint Event (1)": rule_data_list[0],
    "Hint 1-3 Hint Event (1)": rule_data_list[0],
    "Hint 1-4 Hint Event (1)": rule_data_list[0],
    "Hint 1-5 Hint Event (1)": rule_data_list[0],
    "Hint 0-1 Hint Event (1)": rule_data_list[0],
    "Hint 2-1 Hint Event (1)": rule_data_list[26],
    "Hint 2-2 Hint Event (1)": rule_data_list[27],
    "Hint 2-3 Hint Event (1)": rule_data_list[23],
    "Hint 3-1 Hint Event (1)": rule_data_list[0],
    "Hint 3-2 Hint Event (1)": rule_data_list[16],
    "Hint 3-3 Hint Event (1)": rule_data_list[16],
    "Hint 5-1 Hint Event (1)": rule_data_list[19],
    "Hint 5-2 Hint Event (1)": rule_data_list[16],
    "Hint 5-3 Hint Event (1)": rule_data_list[37],
    "Hint 5-4 Hint Event (1)": rule_data_list[51],
    "Hint 5-5 Hint Event (1)": rule_data_list[16],
    "Hint 5-6 Hint Event (1)": rule_data_list[0],
    "Hint 4-1 Hint Event (1)": rule_data_list[0],
    "Hint 4-2 Hint Event (1)": rule_data_list[0],
    "Hint 4-3 Hint Event (1)": rule_data_list[0],
    "Hint 4-4 Hint Event (1)": rule_data_list[1],
    "Hint 4-5 Hint Event (1)": rule_data_list[7],
}
